apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackjack-training.fullname" . }}
  labels:
    {{- include "blackjack-training.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blackjack-training.selectorLabels" . | nindent 4 }}
